### PR TITLE
builder toml rfc

### PR DESCRIPTION
**Pull request by joshzarrabi**
* RFC to implement #27

Readable: https://github.com/joshzarrabi/builder/blob/builder-toml-rfc/rfcs/0002-buildpack-toml-versioning.md

Co-authored-by: Sophie Wigmore <swigmore@vmware.com>

### CODE REVIEW

**Comment by sophiewigmore** [comment]
@ForestEckhardt @sclevine @nebhale tagging you in this PR since I'm not able to add a reviewer

**Comment by ForestEckhardt** [comment]
@joshzarrabi Could you add a readable link to the initial post please?

**Comment by ForestEckhardt** [comment]
@joshzarrabi I only have feed back on readability. If you could move your alternative implementations into a different section that would make this more readable. Other than that I approve.

**Review by ForestEckhardt — APPROVED** [review]

**Review by nebhale — CHANGES_REQUESTED** [review]
Can you please expand this to explicitly state that build image and lifecycle are hard versioned and updated in the same way as the buildpacks.

**Review by sclevine — APPROVED** [review]

**Comment by joshzarrabi** [comment]
@nebhale I added the note about the lifecycle and builder, thanks for pointing that out :)

**Review by nebhale — APPROVED** [review]

**Comment by nebhale** [comment]
@joshzarrabi Approved over here.  Merge and implement at will.

**Pull request merged**
