### PR TITLE
Buildpack ordering rfc

### PR DESCRIPTION
**Pull request by joshzarrabi**

### CODE REVIEW

**Comment by joshzarrabi** [comment]
Sorry for the reverts, please squash before merging :).

**Review by sclevine — APPROVED** [review]

**Review by nebhale — APPROVED** [review]

**Comment by kvedurmu** [comment]
@joshzarrabi this looks great to me. Could you merge it? We'll get separate issues filed to get our builders to conform to this proposal.

**Comment by joshzarrabi** [comment]
@kvedurmu I dont have permission to merge.

**Comment by kvedurmu** [comment]
Ahh forgot about maintainers :). @paketo-buildpacks/release-engineering could y'all merge this?

**Pull request merged**
