### PR TITLE
rfc to change latest tag to base builder

### PR DESCRIPTION
**Pull request by martyspiewak**
[Readable](https://github.com/paketo-buildpacks/builder/blob/rfc-change-latest-to-base/rfcs/0000-template.md)

### CODE REVIEW

**Review by fg-j — COMMENTED** [review]
This makes sense to me overall. My only concern is that we'll need to be very clear about documenting this for users who might experience this as a change. 

Where/how do we currently document that `:latest` points to the full builder, and how can we best alert users to this change?

**Comment by martyspiewak** [comment]
I don't think we document it anywhere actually. Everywhere we document the builder locations we mention the specific tags (`builder:base`, `builder:full`, etc) so I'm not sure there's a place to alert users of this.

Pack also recommends builders by their specific tags so I'm not sure there would be many users that are using `:latest`.

It may not be so bad to switch it without sending notification as most people are probably not relying on it and even if they are most apps would still run on base. Plus, it's pretty easy for them to switch and point to `:full` if their app needs to run on full.

Definitely hear the concern, I'm just not sure there's a great way for us to let people know about the change anyway.

**Comment by arjun024** [comment]
Do we even need a `latest` tag? Could be a potential source of confusion

**Comment by martyspiewak** [comment]
That's interesting. I think that would be fine too.

**Comment by kvedurmu** [comment]
+1 behind defaulting to the base builder as much as possible. I think we should continue publishing the `latest` tag because users frequently just `docker pull paketobuildpacks/builder` and it's referenced in several external sources (notably spring blog posts)

**Review by ekcasey — APPROVED** [review]

**Review by fg-j — APPROVED** [review]

**Pull request merged**
